<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'product_type_id'=>1,
                'name'=>'TARVA',
                'image'=>'assets/products/20.jpg',
                'desc'=>'Bed frame, pine/Luröy',
                'price'=>2699000,
                'stock'=>71,
            ],
            [
                'product_type_id'=>1,
                'name'=>'GJÖRA',
                'image'=>'assets/products/21.jpg',
                'desc'=>'Bed frame, birch/Luröy',
                'price'=>5699000,
                'stock'=>71,
            ],
            [
                'product_type_id'=>1,
                'name'=>'DELAKTIG',
                'image'=>'assets/products/22.jpg',
                'desc'=>'Bed frame/headboard/2 side tables, aluminium/black',
                'price'=>8798000,
                'stock'=>12,
            ],
            [
                'product_type_id'=>1,
                'name'=>'HAUGA',
                'image'=>'assets/products/23.jpg',
                'desc'=>'Upholstered bed frame, Vissle grey',
                'price'=>2299000,
                'stock'=>36,
            ],
            [
                'product_type_id'=>1,
                'name'=>'MALM',
                'image'=>'assets/products/24.jpg',
                'desc'=>'Bed frame, high, brown stained ash veneer/Luröy',
                'price'=>2799000,
                'stock'=>18,
            ],
            [
                'product_type_id'=>1,
                'name'=>'SLATTUM',
                'image'=>'assets/products/25.jpg',
                'desc'=>'Upholstered bed frame, Knisa light grey',
                'price'=>2999000,
                'stock'=>59,
            ],
            [
                'product_type_id'=>1,
                'name'=>'LEIRVIK',
                'image'=>'assets/products/26.jpg',
                'desc'=>'Bed frame, white/Lönset',
                'price'=>3999000,
                'stock'=>49,
                
            ],
            [
                'product_type_id'=>1,
                'name'=>'TYSSEDAL',
                'image'=>'assets/products/27.jpg',
                'desc'=>'Bed frame, white/Luröy',
                'price'=>4599000,
                'stock'=>4,
            ],
            [
                'product_type_id'=>1,
                'name'=>'TUFJORD',
                'image'=>'assets/products/28.jpg',
                'desc'=>'Upholstered bed frame, Djuparp dark green',
                'price'=>9999000,
                'stock'=>10,
                
            ],
            [
                'product_type_id'=>1,
                'name'=>'SAGSTUA',
                'image'=>'assets/products/29.jpg',
                'desc'=>'Bed frame, white/Luröy',
                'price'=>2899000,
                'stock'=>97,
            ],
            [
                'product_type_id'=>1,
                'name'=>'GRIMSBU',
                'image'=>'assets/products/210.jpg',
                'desc'=>'Bed frame, white/Luröy',
                'price'=>1499000,
                'stock'=>50,
            ],
            [
                'product_type_id'=>1,
                'name'=>'ASKVOLL',
                'image'=>'assets/products/211.jpg',
                'desc'=>'Bed frame, white/Luröy',
                'price'=>3499000,
                'stock'=>28,
            ],
            [
                'product_type_id'=>1,
                'name'=>'SONGESAND',
                'image'=>'assets/products/212.jpg',
                'desc'=>'Bed frame, brown/Lönset',
                'price'=>4299000,
                'stock'=>26,
            ],
            [
                'product_type_id'=>1,
                'name'=>'RAKKESTAD',
                'image'=>'assets/products/90.jpg',
                'desc'=>'Wardrobe with sliding doors, black-brown',
                'price'=>2799000,
                'stock'=>39,
            ],
            [
                'product_type_id'=>1,
                'name'=>'RAKKESTAD',
                'image'=>'assets/products/91.jpg',
                'desc'=>'Wardrobe with 3 doors, black-brown',
                'price'=>2399000,
                'stock'=>27,
            ],
            [
                'product_type_id'=>1,
                'name'=>'KLEPPSTAD',
                'image'=>'assets/products/92.jpg',
                'desc'=>'Wardrobe with 2 doors, white',
                'price'=>1399000,
                'stock'=>42,
            ],
            [
                'product_type_id'=>1,
                'name'=>'BRIMNES',
                'image'=>'assets/products/93.jpg',
                'desc'=>'Wardrobe with 3 doors, white',
                'price'=>2599000,
                'stock'=>39,
            ],
            [
                'product_type_id'=>1,
                'name'=>'MUSKEN',
                'image'=>'assets/products/94.jpg',
                'desc'=>'Wardrobe with 2 doors+3 drawers, white',
                'price'=>3999000,
                'stock'=>10,
            ],
            [
                'product_type_id'=>1,
                'name'=>'TRYSIL',
                'image'=>'assets/products/95.jpg',
                'desc'=>'Wardrobe, white/mirror glass',
                'price'=>3499000,
                'stock'=>16,
            ],
            [
                'product_type_id'=>1,
                'name'=>'SYVDE',
                'image'=>'assets/products/96.jpg',
                'desc'=>'Open wardrobe, white',
                'price'=>2000000,
                'stock'=>48,
            ],
            [
                'product_type_id'=>1,
                'name'=>'VISTHUS',
                'image'=>'assets/products/97.jpg',
                'desc'=>'Wardrobe, grey/white',
                'price'=>5999000,
                'stock'=>13,
            ],
            [
                'product_type_id'=>1,
                'name'=>'VUKU',
                'image'=>'assets/products/98.jpg',
                'desc'=>'Wardrobe, white',
                'price'=>299000,
                'stock'=>39,
            ],
            [
                'product_type_id'=>1,
                'name'=>'SONGESAND',
                'image'=>'assets/products/99.jpg',
                'desc'=>'Wardrobe, brown',
                'price'=>3499000,
                'stock'=>19,
            ],
            [
                'product_type_id'=>1,
                'name'=>'TYSSEDAL',
                'image'=>'assets/products/910.jpg',
                'desc'=>'Wardrobe, white/mirror glass',
                'price'=>5999000,
                'stock'=>4,
            ],
            [
                'product_type_id'=>1,
                'name'=>'NORDKISA',
                'image'=>'assets/products/911.jpg',
                'desc'=>'Open wardrobe with sliding door, bamboo',
                'price'=>3299000,
                'stock'=>18,
            ],
            [
                'product_type_id'=>1,
                'name'=>'HEMNES',
                'image'=>'assets/products/912.jpg',
                'desc'=>'Open wardrobe, white stained',
                'price'=>2999000,
                'stock'=>28,
            ],

            [
                'product_type_id'=>2,
                'name'=>'GODMORGON',
                'image'=>'assets/products/10.jpg',
                'desc'=>'Wash-stand with 2 drawers, white stained oak effect',
                'price'=>2995000,
                'stock'=>53,
            ],
            [
                'product_type_id'=>2,
                'name'=>'LILLÅNGEN',
                'image'=>'assets/products/11.jpg',
                'desc'=>'Mirror cabinet with 2 door, white',
                'price'=>795000,
                'stock'=>34,
            ],
            [
                'product_type_id'=>2,
                'name'=>'HEMNES',
                'image'=>'assets/products/12.jpg',
                'desc'=>'Storage bench w towel rail/4 hooks, black-brown',
                'price'=>249000,
                'stock'=>63,
            ],
            [
                'product_type_id'=>2,
                'name'=>'TYNGEN',
                'image'=>'assets/products/13.jpg',
                'desc'=>'Wash-basin, white/Pilkån tap',
                'price'=>1790000,
                'stock'=>'32',
            ],
            [
                'product_type_id'=>2,
                'name'=>'SILVERÅN',
                'image'=>'assets/products/14.jpg',
                'desc'=>'High cabinet with 2 doors, white',
                'price'=>1895000,
                'stock'=>51,
            ],
            [
                'product_type_id'=>2,
                'name'=>'HEMNES/TÖRNVIKEN',
                'image'=>'assets/products/15.jpg',
                'desc'=>'Open wash-stand with 45 wash-basin, black-brown stained/Voxnan tap',
                'price'=>5885000,
                'stock'=>83,
            ],
            [
                'product_type_id'=>2,
                'name'=>'TOLKEN/GODMORGON',
                'image'=>'assets/products/16.jpg',
                'desc'=>'Wash-stand with 2 drawers, white/anthracite',
                'price'=>3495000,
                'stock'=>78,
            ],
            [
                'product_type_id'=>2,
                'name'=>'TYNGEN/RÅGRUND',
                'image'=>'assets/products/17.jpg',
                'desc'=>'Wash-basin/corner shelf, bamboo/Pilkån tap',
                'price'=>2788000,
                'stock'=>19,
            ],
            [
                'product_type_id'=>2,
                'name'=>'TOLKEN',
                'image'=>'assets/products/18.jpg',
                'desc'=>'Countertop, marble effect',
                'price'=>1000000,
                'stock'=>38,
            ],
            [
                'product_type_id'=>2,
                'name'=>'VISKAN',
                'image'=>'assets/products/19.jpg',
                'desc'=>'Countertop, grey',
                'price'=>250000,
                'stock'=>91,
            ],
            [
                'product_type_id'=>2,
                'name'=>'KATTEVIK/HEMNES',
                'image'=>'assets/products/110.jpg',
                'desc'=>'Open wash-stand with 40 wash-basin, white/Voxnan tap',
                'price'=>6585000,
                'stock'=>74,
            ],
            [
                'product_type_id'=>2,
                'name'=>'VILTO/ODENSVIK',
                'image'=>'assets/products/111.jpg',
                'desc'=>'Wash-stand with 1 drawer, birch/LUNDSKÄR tap',
                'price'=>5785000,
                'stock'=>39,
            ],
            [
                'product_type_id'=>2,
                'name'=>'DYNAN',
                'image'=>'assets/products/112.jpg',
                'desc'=>'Mirror cabinet with 2 base cabinets, white',
                'price'=>1597000,
                'stock'=>37,
            ],

            [
                'product_type_id'=>3,
                'name'=>'HEMLINGBY',
                'image'=>'assets/products/80.jpg',
                'desc'=>'Two-seat sofa, Bomstad black',
                'price'=>2995000,
                'stock'=>42,
            ],
            [
                'product_type_id'=>3,
                'name'=>'KLIPPAN',
                'image'=>'assets/products/81.jpg',
                'desc'=>'2-seat sofa, Vissle grey',
                'price'=>2895000,
                'stock'=>34,
            ],
            [
                'product_type_id'=>3,
                'name'=>'KNOPPARP',
                'image'=>'assets/products/82.jpg',
                'desc'=>'2-seat sofa, Knisa light grey',
                'price'=>1995000,
                'stock'=>26,
            ],
            [
                'product_type_id'=>3,
                'name'=>'KIVIK',
                'image'=>'assets/products/83.jpg',
                'desc'=>'4-seat sofa, with chaise longue/Grann/Bomstad black',
                'price'=>29990000,
                'stock'=>45,
            ],
            [
                'product_type_id'=>3,
                'name'=>'SÖDERHAMN',
                'image'=>'assets/products/84.jpg',
                'desc'=>'1-seat section, Finnsta white',
                'price'=>4995000,
                'stock'=>8,
            ],
            [
                'product_type_id'=>3,
                'name'=>'LIDHULT',
                'image'=>'assets/products/85.jpg',
                'desc'=>'2-seat sofa, Lejde grey/black',
                'price'=>8995000,
                'stock'=>5,
            ],
            [
                'product_type_id'=>3,
                'name'=>'SÖDERHAMN',
                'image'=>'assets/products/86.jpg',
                'desc'=>'3-seat section, Samsta dark grey',
                'price'=>8495000,
                'stock'=>18,
            ],
            [
                'product_type_id'=>3,
                'name'=>'GRÖNLID',
                'image'=>'assets/products/87.jpg',
                'desc'=>'Chaise longue, Ljungen light red',
                'price'=>7595000,
                'stock'=>36,
            ],
            [
                'product_type_id'=>3,
                'name'=>'VIMLE',
                'image'=>'assets/products/88.jpg',
                'desc'=>'Footstool with storage, Dalstorp multicolour',
                'price'=>2995000,
                'stock'=>21,
            ],
            [
                'product_type_id'=>3,
                'name'=>'EKTORP',
                'image'=>'assets/products/89.jpg',
                'desc'=>'2-seat sofa',
                'price'=>4995000,
                'stock'=>17,
            ],
            [
                'product_type_id'=>3,
                'name'=>'VINLIDEN',
                'image'=>'assets/products/810.jpg',
                'desc'=>'Cover for 2-seat sofa, Hakebo beige',
                'price'=>1600000,
                'stock'=>54,
            ],
            [
                'product_type_id'=>3,
                'name'=>'VALLENTUNA',
                'image'=>'assets/products/811.jpg',
                'desc'=>'2-seat modular sofa, Orrsta olive-green',
                'price'=>15600000,
                'stock'=>37,
            ],
            [
                'product_type_id'=>3,
                'name'=>'DELAKTIG',
                'image'=>'assets/products/812.jpg',
                'desc'=>'2-seat platform, Gunnared beige',
                'price'=>9095000,
                'stock'=>32,
            ],

            [
                'product_type_id'=>4,
                'name'=>'GRUBBAN',
                'image'=>'assets/products/60.jpg',
                'desc'=>'Step stool, white/birch',
                'price'=>249000,
                'stock'=>38,
            ],
            [
                'product_type_id'=>4,
                'name'=>'RÅSHULT',
                'image'=>'assets/products/61.jpg',
                'desc'=>'Trolley, white',
                'price'=>499000,
                'stock'=>61,
            ],
            [
                'product_type_id'=>4,
                'name'=>'NISSAFORS',
                'image'=>'assets/products/62.jpg',
                'desc'=>'Trolley, white',
                'price'=>599000,
                'stock'=>29,
            ],
            [
                'product_type_id'=>4,
                'name'=>'MÄSTERBY',
                'image'=>'assets/products/63.jpg',
                'desc'=>'Step stool, beige',
                'price'=>399000,
                'stock'=>51,
            ],
            [
                'product_type_id'=>4,
                'name'=>'RÅSKOG',
                'image'=>'assets/products/64.jpg',
                'desc'=>'Trolley, white',
                'price'=>699000,
                'stock'=>76,
            ],
            [
                'product_type_id'=>4,
                'name'=>'TORNVIKEN',
                'image'=>'assets/products/65.jpg',
                'desc'=>'Kitchen island, off-white/oak',
                'price'=>6999000,
                'stock'=>30,
            ],
            [
                'product_type_id'=>4,
                'name'=>'VADHOLMA',
                'image'=>'assets/products/66.jpg',
                'desc'=>'Rack for kitchen island, black',
                'price'=>1500000,
                'stock'=>10,
            ],
            [
                'product_type_id'=>4,
                'name'=>'KUNGSFORS',
                'image'=>'assets/products/67.jpg',
                'desc'=>'Kitchen trolley, stainless steel',
                'price'=>2499000,
                'stock'=>65,
            ],
            [
                'product_type_id'=>4,
                'name'=>'STENSTORP',
                'image'=>'assets/products/68.jpg',
                'desc'=>'Kitchen trolley, white/oak',
                'price'=>3999000,
                'stock'=>39,
            ],
            [
                'product_type_id'=>4,
                'name'=>'VADHOLMA',
                'image'=>'assets/products/69.jpg',
                'desc'=>'Kitchen island, black/oak',
                'price'=>7999000,
                'stock'=>56,
            ],
            [
                'product_type_id'=>4,
                'name'=>'RIMFORSA',
                'image'=>'assets/products/610.jpg',
                'desc'=>'Work bench, stainless steel/bamboo',
                'price'=>8999000,
                'stock'=>11,
            ],
            [
                'product_type_id'=>4,
                'name'=>'SUNNERSTA',
                'image'=>'assets/products/611.jpg',
                'desc'=>'Trolley',
                'price'=>399000,
                'stock'=>18,
            ],
            [
                'product_type_id'=>4,
                'name'=>'BEKVÄM',
                'image'=>'assets/products/612.jpg',
                'desc'=>'Step stool, white',
                'price'=>399000,
                'stock'=>32,
            ],

            [
                'product_type_id'=>5,
                'name'=>'IKEA 365+',
                'image'=>'assets/products/40.jpg',
                'desc'=>'Bowl, rounded sides white',
                'price'=>49900,
                'stock'=>19,
            ],
            [
                'product_type_id'=>5,
                'name'=>'DINERA',
                'image'=>'assets/products/41.jpg',
                'desc'=>'18-piece service, beige',
                'price'=>399000,
                'stock'=>29,
            ],
            [
                'product_type_id'=>5,
                'name'=>'FÄRGRIK',
                'image'=>'assets/products/42.jpg',
                'desc'=>'18-piece service, light green',
                'price'=>499000,
                'stock'=>49,
            ],
            [
                'product_type_id'=>5,
                'name'=>'SANNING',
                'image'=>'assets/products/43.jpg',
                'desc'=>'Mug, white',
                'price'=>29900,
                'stock'=>79,
            ],
            [
                'product_type_id'=>5,
                'name'=>'BACKIG',
                'image'=>'assets/products/44.jpg',
                'desc'=>'Side plate, black',
                'price'=>149000,
                'stock'=>93,
            ],
            [
                'product_type_id'=>5,
                'name'=>'ALLEHANDA',
                'image'=>'assets/products/45.jpg',
                'desc'=>'Mixing bowl with lid, green',
                'price'=>179900,
                'stock'=>81,
            ],
            [
                'product_type_id'=>5,
                'name'=>'FLITIGHET',
                'image'=>'assets/products/46.jpg',
                'desc'=>'Bowl, white',
                'price'=>24900,
                'stock'=>100,
            ],
            [
                'product_type_id'=>5,
                'name'=>'VARDAGEN',
                'image'=>'assets/products/47.jpg',
                'desc'=>'Bowl, clear glass',
                'price'=>29900,
                'stock'=>48,
            ],
            [
                'product_type_id'=>5,
                'name'=>'BLANDA',
                'image'=>'assets/products/48.jpg',
                'desc'=>'Serving bowl, clear glass',
                'price'=>29900,
                'stock'=>70,
            ],
            [
                'product_type_id'=>5,
                'name'=>'TRYGG',
                'image'=>'assets/products/49.jpg',
                'desc'=>'Serving bowl, clear glass',
                'price'=>39900,
                'stock'=>40,
            ],
            [
                'product_type_id'=>5,
                'name'=>'KLYFTA',
                'image'=>'assets/products/410.jpg',
                'desc'=>'Bread basket, bamboo',
                'price'=>89900,
                'stock'=>85,
            ],
            [
                'product_type_id'=>5,
                'name'=>'BESEGRA',
                'image'=>'assets/products/411.jpg',
                'desc'=>'Bowl, light turquoise',
                'price'=>99900,
                'stock'=>81,
            ],
            [
                'product_type_id'=>5,
                'name'=>'UPPVISPAD',
                'image'=>'assets/products/412.jpg',
                'desc'=>'Plate, white',
                'price'=>99900,
                'stock'=>19,
            ],
        
            [
                'product_type_id'=>6,
                'name'=>'BILLY',
                'image'=>'assets/products/30.jpg',
                'desc'=>'Bookcase, white',
                'price'=>6786000,
                'stock'=>71,
            ],
            [
                'product_type_id'=>6,
                'name'=>'GERSBY',
                'image'=>'assets/products/31.jpg',
                'desc'=>'Bookcase, white',
                'price'=>599000,
                'stock'=>48,
            ],
            [
                'product_type_id'=>6,
                'name'=>'LIATORP',
                'image'=>'assets/products/32.jpg',
                'desc'=>'Bookcase, white',
                'price'=>4999000,
                'stock'=>53,
            ],
            [
                'product_type_id'=>6,
                'name'=>'BRIMNES',
                'image'=>'assets/products/33.jpg',
                'desc'=>'Bookcase, white',
                'price'=>1799000,
                'stock'=>20,
            ],
            [
                'product_type_id'=>6,
                'name'=>'LAIVA',
                'image'=>'assets/products/34.jpg',
                'desc'=>'Bookcase, black-brown',
                'price'=>399000,
                'stock'=>60,
            ],
            [
                'product_type_id'=>6,
                'name'=>'LOMMARP',
                'image'=>'assets/products/35.jpg',
                'desc'=>'Bookcase, dark blue-green',
                'price'=>2799000,
                'stock'=>16,
            ],
            [
                'product_type_id'=>6,
                'name'=>'BRUSALI',
                'image'=>'assets/products/36.jpg',
                'desc'=>'Bookcase, white',
                'price'=>1799000,
                'stock'=>92,
            ],
            [
                'product_type_id'=>6,
                'name'=>'FINNBY',
                'image'=>'assets/products/37.jpg',
                'desc'=>'Bookcase, black',
                'price'=>899000,
                'stock'=>19,
            ],
            [
                'product_type_id'=>6,
                'name'=>'BILLY/MORLIDEN',
                'image'=>'assets/products/38.jpg',
                'desc'=>'Bookcase with glass-doors, white stained oak veneer/glass',
                'price'=>2399000,
                'stock'=>35,
            ],
            [
                'product_type_id'=>6,
                'name'=>'OXBERG',
                'image'=>'assets/products/39.jpg',
                'desc'=>'Door, white',
                'price'=>500000,
                'stock'=>81,
            ],
            [
                'product_type_id'=>6,
                'name'=>'BILLY/OXBERG',
                'image'=>'assets/products/310.jpg',
                'desc'=>'Bookcase with glass-doors, black-brown',
                'price'=>5348000,
                'stock'=>18,
            ],
            [
                'product_type_id'=>6,
                'name'=>'OXBERG/BILLY',
                'image'=>'assets/products/311.jpg',
                'desc'=>'Bookcase with doors, white',
                'price'=>1799000,
                'stock'=>38,
            ],
            [
                'product_type_id'=>6,
                'name'=>'BILLY/MORLIDEN',
                'image'=>'assets/products/312.jpg',
                'desc'=>'Bookcase with glass door, white stained oak veneer/glass',
                'price'=>1499000,
                'stock'=>54,
            ],
        
            [
                'product_type_id'=>6,
                'name'=>'ARKELSTORP',
                'image'=>'assets/products/50.jpg',
                'desc'=>'Desk, black',
                'price'=>2999000,
                'stock'=>16,
            ],
            [
                'product_type_id'=>6,
                'name'=>'FJÄLLBO',
                'image'=>'assets/products/51.jpg',
                'desc'=>'Laptop table, black',
                'price'=>999000,
                'stock'=>38,
            ],
            [
                'product_type_id'=>6,
                'name'=>'LISABO',
                'image'=>'assets/products/52.jpg',
                'desc'=>'Desk, ash veneer',
                'price'=>2499000,
                'stock'=>61,
            ],
            [
                'product_type_id'=>6,
                'name'=>'MICKE',
                'image'=>'assets/products/53.jpg',
                'desc'=>'Desk, white',
                'price'=>1499000,
                'stock'=>28,
            ],
            [
                'product_type_id'=>6,
                'name'=>'ALEX',
                'image'=>'assets/products/54.jpg',
                'desc'=>'Drawer unit, white',
                'price'=>1370000,
                'stock'=>57,
            ],
            [
                'product_type_id'=>6,
                'name'=>'FREDDE',
                'image'=>'assets/products/55.jpg',
                'desc'=>'Desk, black',
                'price'=>3499000,
                'stock'=>37,
            ],
            [
                'product_type_id'=>6,
                'name'=>'LOMMARP',
                'image'=>'assets/products/56.jpg',
                'desc'=>'Desk, light beige',
                'price'=>2499000,
                'stock'=>37,
            ],
            [
                'product_type_id'=>6,
                'name'=>'MALM',
                'image'=>'assets/products/57.jpg',
                'desc'=>'Desk with pull-out panel, white',
                'price'=>2299000,
                'stock'=>48,
            ],
            [
                'product_type_id'=>6,
                'name'=>'KRILLE/LINNMON',
                'image'=>'assets/products/58.jpg',
                'desc'=>'Desk, white',
                'price'=>1289000,
                'stock'=>13,
            ],
            [
                'product_type_id'=>6,
                'name'=>'ADILS/LINNMON',
                'image'=>'assets/products/59.jpg',
                'desc'=>'Table, white',
                'price'=>549000,
                'stock'=>31,
            ],
            [
                'product_type_id'=>6,
                'name'=>'VITTSJÖ',
                'image'=>'assets/products/510.jpg',
                'desc'=>'Laptop table, white/glass',
                'price'=>699000,
                'stock'=>22,
            ],
            [
                'product_type_id'=>6,
                'name'=>'INGATORP',
                'image'=>'assets/products/511.jpg',
                'desc'=>'Desk, black',
                'price'=>2499000,
                'stock'=>26,
            ],
            [
                'product_type_id'=>6,
                'name'=>'KULLABERG',
                'image'=>'assets/products/512.jpg',
                'desc'=>'Desk, pine/black',
                'price'=>2499000,
                'stock'=>58,
            ],
        
            [
                'product_type_id'=>6,
                'name'=>'MARKUS',
                'image'=>'assets/products/70.jpg',
                'desc'=>'Office chair, Vissle dark grey',
                'price'=>2999000,
                'stock'=>52,
            ],
            [
                'product_type_id'=>6,
                'name'=>'LÅNGFJÄLL',
                'image'=>'assets/products/71.jpg',
                'desc'=>'Conference chair, Gunnared dark grey/white',
                'price'=>1999000,
                'stock'=>43,
            ],
            [
                'product_type_id'=>6,
                'name'=>'LIDKULLEN',
                'image'=>'assets/products/72.jpg',
                'desc'=>'Active sit/stand support, Gunnared beige',
                'price'=>1499000,
                'stock'=>38,
            ],
            [
                'product_type_id'=>6,
                'name'=>'TROLLBERGET',
                'image'=>'assets/products/73.jpg',
                'desc'=>'Active sit/stand support, Grann beige',
                'price'=>1999000,
                'stock'=>71,
            ],
            [
                'product_type_id'=>6,
                'name'=>'HATTEFJÄLL',
                'image'=>'assets/products/74.jpg',
                'desc'=>'Office chair, Gunnared beige',
                'price'=>4999000,
                'stock'=>39,
            ],
            [
                'product_type_id'=>6,
                'name'=>'ALEFJÄLL',
                'image'=>'assets/products/75.jpg',
                'desc'=>'Office chair, Grann golden-brown',
                'price'=>4999000,
                'stock'=>39,
            ],
            [
                'product_type_id'=>6,
                'name'=>'FLINTAN',
                'image'=>'assets/products/76.jpg',
                'desc'=>'Office chair, Vissle grey',
                'price'=>999000,
                'stock'=>28,
            ],
            [
                'product_type_id'=>6,
                'name'=>'FJÄLLBERGET',
                'image'=>'assets/products/77.jpg',
                'desc'=>'Conference chair with castors, black stained ash veneer/Gunnared dark grey',
                'price'=>3299000,
                'stock'=>29,
            ],
            [
                'product_type_id'=>6,
                'name'=>'JÄRVFJÄLLET',
                'image'=>'assets/products/78.jpg',
                'desc'=>'Office chair with armrests, Gunnared dark grey/black',
                'price'=>3499000,
                'stock'=>13,
            ],
            [
                'product_type_id'=>6,
                'name'=>'FLINTAN/NOMINELL',
                'image'=>'assets/products/79.jpg',
                'desc'=>'Office chair with armrests, black',
                'price'=>1249000,
                'stock'=>31,
            ],
            [
                'product_type_id'=>6,
                'name'=>'LÅNGFJÄLL',
                'image'=>'assets/products/710.jpg',
                'desc'=>'Office chair with armrests, Gunnared light brown-pink/white',
                'price'=>3199000,
                'stock'=>69,
            ],
            [
                'product_type_id'=>6,
                'name'=>'LÅNGFJÄLL',
                'image'=>'assets/products/711.jpg',
                'desc'=>'Conference chair with armrests, Gunnared blue/black',
                'price'=>2499000,
                'stock'=>71,
            ],
            [
                'product_type_id'=>6,
                'name'=>'JÄRVFJÄLLET',
                'image'=>'assets/products/712.jpg',
                'desc'=>'Office chair with armrests, Gunnared beige/white',
                'price'=>3499000,
                'stock'=>38,
            ]
        ]);
    }
}