<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'product_type_id'=>1,
                'name'=>'GODMORGON',
                'image'=>'10.jpg',
                'desc'=>'Wash-stand with 2 drawers, white stained oak effect',
                'price'=>2995000,
                'stock'=>53,
            ],
            [
                'product_type_id'=>1,
                'name'=>'LILLÅNGEN',
                'image'=>'11.jpg',
                'desc'=>'Mirror cabinet with 1 door, white',
                'price'=>795000,
                'stock'=>34,
            ],
            [
                'product_type_id'=>1,
                'name'=>'HEMNES',
                'image'=>'12.jpg',
                'desc'=>'High cabinet with glass door, black-brown',
                'price'=>249000,
                'stock'=>63,
            ],
            [
                'product_type_id'=>1,
                'name'=>'TYNGEN',
                'image'=>'13.jpg',
                'desc'=>'Wash-basin, white/Pilkån tap',
                'price'=>1790000,
                'stock'=>'32',
            ],
            [
                'product_type_id'=>1,
                'name'=>'SILVERÅN',
                'image'=>'14.jpg',
                'desc'=>'High cabinet with 2 doors, white',
                'price'=>1895000,
                'stock'=>51,
            ],
            [
                'product_type_id'=>1,
                'name'=>'HEMNES/HAGAVIKEN',
                'image'=>'15.jpg',
                'desc'=>'Wash-stand with 2 drawers, black-brown',
                'price'=>3990000,
                'stock'=>83,
            ],
            [
                'product_type_id'=>1,
                'name'=>'TOLKEN/GODMORGON',
                'image'=>'16.jpg',
                'desc'=>'Wash-stand with 2 drawers, white/anthracite',
                'price'=>3495000,
                'stock'=>78,
            ],
            [
                'product_type_id'=>1,
                'name'=>'TYNGEN/RÅGRUND',
                'image'=>'17.jpg',
                'desc'=>'Wash-basin/corner shelf, bamboo/Pilkån tap',
                'price'=>2788000,
                'stock'=>19,
            ],
            [
                'product_type_id'=>1,
                'name'=>'TOLKEN',
                'image'=>'18.jpg',
                'desc'=>'Countertop, marble effect',
                'price'=>1000000,
                'stock'=>38,
            ],
            [
                'product_type_id'=>1,
                'name'=>'VISKAN',
                'image'=>'19.jpg',
                'desc'=>'Countertop, grey',
                'price'=>250000,
                'stock'=>91,
            ],
            [
                'product_type_id'=>1,
                'name'=>'KATTEVIK/HEMNES',
                'image'=>'110.jpg',
                'desc'=>'Open wash-stand with 40 wash-basin, white/Voxnan tap',
                'price'=>6585000,
                'stock'=>74,
            ],
            [
                'product_type_id'=>1,
                'name'=>'VILTO/ODENSVIK',
                'image'=>'111.jpg',
                'desc'=>'Wash-stand with 1 drawer, birch/LUNDSKÄR tap',
                'price'=>5785000,
                'stock'=>39,
            ],
            [
                'product_type_id'=>1,
                'name'=>'DYNAN',
                'image'=>'112.jpg',
                'desc'=>'Mirror cabinet with 2 base cabinets, white',
                'price'=>1597000,
                'stock'=>37,
            ],
        
            [
                'product_type_id'=>2,
                'name'=>'TARVA',
                'image'=>'20.jpg',
                'desc'=>'Bed frame, birch/Luröy',
                'price'=>5699000,
                'stock'=>71,
            ],
            [
                'product_type_id'=>2,
                'name'=>'GJÖRA',
                'image'=>'21.jpg',
                'desc'=>'Bed frame, birch/Luröy',
                'price'=>5699000,
                'stock'=>71,
            ],
            [
                'product_type_id'=>2,
                'name'=>'DELAKTIG',
                'image'=>'22.jpg',
                'desc'=>'Bed frame with headboard, aluminium/black',
                'price'=>6798000,
                'stock'=>12,
            ],
            [
                'product_type_id'=>2,
                'name'=>'HAUGA',
                'image'=>'23.jpg',
                'desc'=>'Upholstered bed frame, Vissle grey',
                'price'=>2299000,
                'stock'=>36,
            ],
            [
                'product_type_id'=>2,
                'name'=>'MALM',
                'image'=>'24.jpg',
                'desc'=>'Bed frame, high, brown stained ash veneer/Luröy',
                'price'=>2799000,
                'stock'=>18,
            ],
            [
                'product_type_id'=>2,
                'name'=>'SLATTUM',
                'image'=>'25.jpg',
                'desc'=>'Upholstered bed frame, Knisa light grey',
                'price'=>2999000,
                'stock'=>59,
            ],
            [
                'product_type_id'=>2,
                'name'=>'LEIRVIK',
                'image'=>'26.jpg',
                'desc'=>'Bed frame, white/Lönset',
                'price'=>3999000,
                'stock'=>49,
                
            ],
            [
                'product_type_id'=>2,
                'name'=>'TYSSEDAL',
                'image'=>'27.jpg',
                'desc'=>'Bed frame, white/Luröy',
                'price'=>4599000,
                'stock'=>4,
            ],
            [
                'product_type_id'=>2,
                'name'=>'TUFJORD',
                'image'=>'28.jpg',
                'desc'=>'Upholstered bed frame, Djuparp dark green',
                'price'=>9999000,
                'stock'=>10,
                
            ],
            [
                'product_type_id'=>2,
                'name'=>'SAGSTUA',
                'image'=>'29.jpg',
                'desc'=>'Bed frame, white/Luröy',
                'price'=>2899000,
                'stock'=>97,
            ],
            [
                'product_type_id'=>2,
                'name'=>'GRIMSBU',
                'image'=>'210.jpg',
                'desc'=>'Bed frame, white/Luröy',
                'price'=>1499000,
                'stock'=>50,
            ],
            [
                'product_type_id'=>2,
                'name'=>'ASKVOLL',
                'image'=>'211.jpg',
                'desc'=>'Bed frame, white/Luröy',
                'price'=>3499000,
                'stock'=>28,
            ],
            [
                'product_type_id'=>2,
                'name'=>'SONGESAND',
                'image'=>'212.jpg',
                'desc'=>'Bed frame, brown/Lönset',
                'price'=>4299000,
                'stock'=>26,
            ],
        
            [
                'product_type_id'=>3,
                'name'=>'BILLY',
                'image'=>'30.jpg',
                'desc'=>'Bookcase, white',
                'price'=>1799000,
                'stock'=>71,
            ],
            [
                'product_type_id'=>3,
                'name'=>'GERSBY',
                'image'=>'31.jpg',
                'desc'=>'Bookcase, white',
                'price'=>599000,
                'stock'=>48,
            ],
            [
                'product_type_id'=>3,
                'name'=>'LIATORP',
                'image'=>'32.jpg',
                'desc'=>'Bookcase, white',
                'price'=>4999000,
                'stock'=>53,
            ],
            [
                'product_type_id'=>3,
                'name'=>'BRIMNES',
                'image'=>'33.jpg',
                'desc'=>'Bookcase, white',
                'price'=>1799000,
                'stock'=>20,
            ],
            [
                'product_type_id'=>3,
                'name'=>'LAIVA',
                'image'=>'34.jpg',
                'desc'=>'Bookcase, black-brown',
                'price'=>399000,
                'stock'=>60,
            ],
            [
                'product_type_id'=>3,
                'name'=>'LOMMARP',
                'image'=>'35.jpg',
                'desc'=>'Bookcase, dark blue-green',
                'price'=>2799000,
                'stock'=>16,
            ],
            [
                'product_type_id'=>3,
                'name'=>'BRUSALI',
                'image'=>'36.jpg',
                'desc'=>'Bookcase, white',
                'price'=>1799000,
                'stock'=>92,
            ],
            [
                'product_type_id'=>3,
                'name'=>'FINNBY',
                'image'=>'37.jpg',
                'desc'=>'Bookcase, black',
                'price'=>899000,
                'stock'=>19,
            ],
            [
                'product_type_id'=>3,
                'name'=>'BILLY/MORLIDEN',
                'image'=>'38.jpg',
                'desc'=>'Bookcase with glass-doors, white stained oak veneer/glass',
                'price'=>2399000,
                'stock'=>35,
            ],
            [
                'product_type_id'=>3,
                'name'=>'OXBERG',
                'image'=>'39.jpg',
                'desc'=>'Door, white',
                'price'=>500000,
                'stock'=>81,
            ],
            [
                'product_type_id'=>3,
                'name'=>'BILLY/OXBERG',
                'image'=>'310.jpg',
                'desc'=>'Bookcase with glass-doors, black-brown',
                'price'=>5348000,
                'stock'=>18,
            ],
            [
                'product_type_id'=>3,
                'name'=>'OXBERG/BILLY',
                'image'=>'311.jpg',
                'desc'=>'Bookcase with doors, white',
                'price'=>1799000,
                'stock'=>38,
            ],
            [
                'product_type_id'=>3,
                'name'=>'BILLY/MORLIDEN',
                'image'=>'312.jpg',
                'desc'=>'Bookcase with glass door, white stained oak veneer/glass',
                'price'=>1499000,
                'stock'=>54,
            ],
        
            [
                'product_type_id'=>4,
                'name'=>'IKEA 365+',
                'image'=>'40.jpg',
                'desc'=>'Bowl, rounded sides white',
                'price'=>49900,
                'stock'=>19,
            ],
            [
                'product_type_id'=>4,
                'name'=>'DINERA',
                'image'=>'41.jpg',
                'desc'=>'18-piece service, beige',
                'price'=>399000,
                'stock'=>29,
            ],
            [
                'product_type_id'=>4,
                'name'=>'FÄRGRIK',
                'image'=>'42.jpg',
                'desc'=>'18-piece service, light green',
                'price'=>499000,
                'stock'=>49,
            ],
            [
                'product_type_id'=>4,
                'name'=>'SANNING',
                'image'=>'43.jpg',
                'desc'=>'Bowl, white/patterned',
                'price'=>29900,
                'stock'=>79,
            ],
            [
                'product_type_id'=>4,
                'name'=>'UTEFEST',
                'image'=>'44.jpg',
                'desc'=>'Side plate, mixed colours',
                'price'=>49900,
                'stock'=>93,
            ],
            [
                'product_type_id'=>4,
                'name'=>'SPORADISK',
                'image'=>'45.jpg',
                'desc'=>'Bowl, angled sides white/blue',
                'price'=>49900,
                'stock'=>81,
            ],
            [
                'product_type_id'=>4,
                'name'=>'FLITIGHET',
                'image'=>'46.jpg',
                'desc'=>'Bowl, white',
                'price'=>24900,
                'stock'=>100,
            ],
            [
                'product_type_id'=>4,
                'name'=>'VARDAGEN',
                'image'=>'47.jpg',
                'desc'=>'Bowl, clear glass',
                'price'=>29900,
                'stock'=>48,
            ],
            [
                'product_type_id'=>4,
                'name'=>'BLANDA',
                'image'=>'48.jpg',
                'desc'=>'Serving bowl, clear glass',
                'price'=>29900,
                'stock'=>70,
            ],
            [
                'product_type_id'=>4,
                'name'=>'TRYGG',
                'image'=>'49.jpg',
                'desc'=>'Serving bowl, clear glass',
                'price'=>39900,
                'stock'=>40,
            ],
            [
                'product_type_id'=>4,
                'name'=>'KLYFTA',
                'image'=>'410.jpg',
                'desc'=>'Bread basket, bamboo',
                'price'=>89900,
                'stock'=>85,
            ],
            [
                'product_type_id'=>4,
                'name'=>'BESEGRA',
                'image'=>'411.jpg',
                'desc'=>'Bowl, light turquoise',
                'price'=>99900,
                'stock'=>81,
            ],
            [
                'product_type_id'=>4,
                'name'=>'UPPVISPAD',
                'image'=>'412.jpg',
                'desc'=>'Plate, white',
                'price'=>99900,
                'stock'=>19,
            ],
        
            [
                'product_type_id'=>5,
                'name'=>'ARKELSTORP',
                'image'=>'50.jpg',
                'desc'=>'Desk, black',
                'price'=>2999000,
                'stock'=>16,
            ],
            [
                'product_type_id'=>5,
                'name'=>'FJÄLLBO',
                'image'=>'51.jpg',
                'desc'=>'Laptop table, black',
                'price'=>999000,
                'stock'=>38,
            ],
            [
                'product_type_id'=>5,
                'name'=>'LISABO',
                'image'=>'52.jpg',
                'desc'=>'Desk, ash veneer',
                'price'=>2499000,
                'stock'=>61,
            ],
            [
                'product_type_id'=>5,
                'name'=>'MICKE',
                'image'=>'53.jpg',
                'desc'=>'Desk, white',
                'price'=>1499000,
                'stock'=>28,
            ],
            [
                'product_type_id'=>5,
                'name'=>'ALEX',
                'image'=>'54.jpg',
                'desc'=>'Drawer unit, white',
                'price'=>1370000,
                'stock'=>57,
            ],
            [
                'product_type_id'=>5,
                'name'=>'FREDDE',
                'image'=>'55.jpg',
                'desc'=>'Desk, black',
                'price'=>3499000,
                'stock'=>37,
            ],
            [
                'product_type_id'=>5,
                'name'=>'LOMMARP',
                'image'=>'56.jpg',
                'desc'=>'Desk, light beige',
                'price'=>2499000,
                'stock'=>37,
            ],
            [
                'product_type_id'=>5,
                'name'=>'MALM',
                'image'=>'57.jpg',
                'desc'=>'Desk with pull-out panel, white',
                'price'=>2299000,
                'stock'=>48,
            ],
            [
                'product_type_id'=>5,
                'name'=>'KRILLE/LINNMON',
                'image'=>'58.jpg',
                'desc'=>'Desk, white',
                'price'=>1289000,
                'stock'=>13,
            ],
            [
                'product_type_id'=>5,
                'name'=>'ADILS/LINNMON',
                'image'=>'59.jpg',
                'desc'=>'Table, white',
                'price'=>549000,
                'stock'=>31,
            ],
            [
                'product_type_id'=>5,
                'name'=>'VITTSJÖ',
                'image'=>'510.jpg',
                'desc'=>'Laptop table, white/glass',
                'price'=>699000,
                'stock'=>22,
            ],
            [
                'product_type_id'=>5,
                'name'=>'INGATORP',
                'image'=>'511.jpg',
                'desc'=>'Desk, black',
                'price'=>2499000,
                'stock'=>26,
            ],
            [
                'product_type_id'=>5,
                'name'=>'KULLABERG',
                'image'=>'512.jpg',
                'desc'=>'Desk, pine/black',
                'price'=>2499000,
                'stock'=>58,
            ],
        
            [
                'product_type_id'=>6,
                'name'=>'GRUBBAN',
                'image'=>'60.jpg',
                'desc'=>'Step stool, white/birch',
                'price'=>249000,
                'stock'=>38,
            ],
            [
                'product_type_id'=>6,
                'name'=>'RÅSHULT',
                'image'=>'61.jpg',
                'desc'=>'Trolley, white',
                'price'=>499000,
                'stock'=>61,
            ],
            [
                'product_type_id'=>6,
                'name'=>'NISSAFORS',
                'image'=>'62.jpg',
                'desc'=>'Trolley, white',
                'price'=>599000,
                'stock'=>29,
            ],
            [
                'product_type_id'=>6,
                'name'=>'MÄSTERBY',
                'image'=>'63.jpg',
                'desc'=>'Step stool, brown-red',
                'price'=>399000,
                'stock'=>51,
            ],
            [
                'product_type_id'=>6,
                'name'=>'RÅSKOG',
                'image'=>'64.jpg',
                'desc'=>'Trolley, white',
                'price'=>699000,
                'stock'=>76,
            ],
            [
                'product_type_id'=>6,
                'name'=>'TORNVIKEN',
                'image'=>'65.jpg',
                'desc'=>'Kitchen island, off-white/oak',
                'price'=>6999000,
                'stock'=>30,
            ],
            [
                'product_type_id'=>6,
                'name'=>'VADHOLMA',
                'image'=>'66.jpg',
                'desc'=>'Rack for kitchen island, black',
                'price'=>1500000,
                'stock'=>10,
            ],
            [
                'product_type_id'=>6,
                'name'=>'KUNGSFORS',
                'image'=>'67.jpg',
                'desc'=>'Kitchen trolley, stainless steel',
                'price'=>2499000,
                'stock'=>65,
            ],
            [
                'product_type_id'=>6,
                'name'=>'STENSTORP',
                'image'=>'68.jpg',
                'desc'=>'Kitchen trolley, white/oak',
                'price'=>3999000,
                'stock'=>39,
            ],
            [
                'product_type_id'=>6,
                'name'=>'VADHOLMA',
                'image'=>'69.jpg',
                'desc'=>'Kitchen island, black/oak',
                'price'=>7999000,
                'stock'=>56,
            ],
            [
                'product_type_id'=>6,
                'name'=>'RIMFORSA',
                'image'=>'610.jpg',
                'desc'=>'Work bench, stainless steel/bamboo',
                'price'=>8999000,
                'stock'=>11,
            ],
            [
                'product_type_id'=>6,
                'name'=>'SUNNERSTA',
                'image'=>'611.jpg',
                'desc'=>'Trolley',
                'price'=>399000,
                'stock'=>18,
            ],
            [
                'product_type_id'=>6,
                'name'=>'BEKVÄM',
                'image'=>'612.jpg',
                'desc'=>'Step stool, white',
                'price'=>399000,
                'stock'=>32,
            ],
        
            [
                'product_type_id'=>7,
                'name'=>'MARKUS',
                'image'=>'70.jpg',
                'desc'=>'Office chair, Vissle dark grey',
                'price'=>2999000,
                'stock'=>52,
            ],
            [
                'product_type_id'=>7,
                'name'=>'LÅNGFJÄLL',
                'image'=>'71.jpg',
                'desc'=>'Conference chair, Gunnared dark grey/white',
                'price'=>1999000,
                'stock'=>43,
            ],
            [
                'product_type_id'=>7,
                'name'=>'LIDKULLEN',
                'image'=>'72.jpg',
                'desc'=>'Active sit/stand support, Gunnared beige',
                'price'=>1499000,
                'stock'=>38,
            ],
            [
                'product_type_id'=>7,
                'name'=>'TROLLBERGET',
                'image'=>'73.jpg',
                'desc'=>'Active sit/stand support, Grann beige',
                'price'=>1999000,
                'stock'=>71,
            ],
            [
                'product_type_id'=>7,
                'name'=>'HATTEFJÄLL',
                'image'=>'74.jpg',
                'desc'=>'Office chair, Gunnared beige',
                'price'=>4999000,
                'stock'=>39,
            ],
            [
                'product_type_id'=>7,
                'name'=>'ALEFJÄLL',
                'image'=>'75.jpg',
                'desc'=>'Office chair, Grann golden-brown',
                'price'=>4999000,
                'stock'=>39,
            ],
            [
                'product_type_id'=>7,
                'name'=>'FLINTAN',
                'image'=>'76.jpg',
                'desc'=>'Office chair, Vissle grey',
                'price'=>999000,
                'stock'=>28,
            ],
            [
                'product_type_id'=>7,
                'name'=>'FJÄLLBERGET',
                'image'=>'77.jpg',
                'desc'=>'Conference chair with castors, black stained ash veneer/Gunnared dark grey',
                'price'=>3299000,
                'stock'=>29,
            ],
            [
                'product_type_id'=>7,
                'name'=>'JÄRVFJÄLLET',
                'image'=>'78.jpg',
                'desc'=>'Office chair with armrests, Gunnared dark grey/black',
                'price'=>3499000,
                'stock'=>13,
            ],
            [
                'product_type_id'=>7,
                'name'=>'FLINTAN/NOMINELL',
                'image'=>'79.jpg',
                'desc'=>'Office chair with armrests, black',
                'price'=>1249000,
                'stock'=>31,
            ],
            [
                'product_type_id'=>7,
                'name'=>'LÅNGFJÄLL',
                'image'=>'710.jpg',
                'desc'=>'Office chair with armrests, Gunnared light brown-pink/white',
                'price'=>3199000,
                'stock'=>69,
            ],
            [
                'product_type_id'=>7,
                'name'=>'LÅNGFJÄLL',
                'image'=>'711.jpg',
                'desc'=>'Conference chair with armrests, Gunnared blue/black',
                'price'=>2499000,
                'stock'=>71,
            ],
            [
                'product_type_id'=>7,
                'name'=>'JÄRVFJÄLLET',
                'image'=>'712.jpg',
                'desc'=>'Office chair with armrests, Gunnared beige/white',
                'price'=>3499000,
                'stock'=>38,
            ],
        
            [
                'product_type_id'=>8,
                'name'=>'HEMLINGBY',
                'image'=>'80.jpg',
                'desc'=>'Two-seat sofa, Bomstad black',
                'price'=>2995000,
                'stock'=>42,
            ],
            [
                'product_type_id'=>8,
                'name'=>'KLIPPAN',
                'image'=>'81.jpg',
                'desc'=>'2-seat sofa, Vissle grey',
                'price'=>2895000,
                'stock'=>34,
            ],
            [
                'product_type_id'=>8,
                'name'=>'KNOPPARP',
                'image'=>'82.jpg',
                'desc'=>'2-seat sofa, Knisa light grey',
                'price'=>1995000,
                'stock'=>26,
            ],
            [
                'product_type_id'=>8,
                'name'=>'KIVIK',
                'image'=>'83.jpg',
                'desc'=>'4-seat sofa, with chaise longue/Grann/Bomstad black',
                'price'=>29990000,
                'stock'=>45,
            ],
            [
                'product_type_id'=>8,
                'name'=>'SÖDERHAMN',
                'image'=>'84.jpg',
                'desc'=>'1-seat section, Finnsta white',
                'price'=>4995000,
                'stock'=>8,
            ],
            [
                'product_type_id'=>8,
                'name'=>'LIDHULT',
                'image'=>'85.jpg',
                'desc'=>'2-seat sofa, Lejde grey/black',
                'price'=>8995000,
                'stock'=>5,
            ],
            [
                'product_type_id'=>8,
                'name'=>'SÖDERHAMN',
                'image'=>'86.jpg',
                'desc'=>'3-seat section, Samsta dark grey',
                'price'=>8495000,
                'stock'=>18,
            ],
            [
                'product_type_id'=>8,
                'name'=>'GRÖNLID',
                'image'=>'87.jpg',
                'desc'=>'Chaise longue, Ljungen light red',
                'price'=>7595000,
                'stock'=>36,
            ],
            [
                'product_type_id'=>8,
                'name'=>'VIMLE',
                'image'=>'88.jpg',
                'desc'=>'Footstool with storage, Dalstorp multicolour',
                'price'=>2995000,
                'stock'=>21,
            ],
            [
                'product_type_id'=>8,
                'name'=>'EKTORP',
                'image'=>'89.jpg',
                'desc'=>'2-seat sofa',
                'price'=>4995000,
                'stock'=>17,
            ],
            [
                'product_type_id'=>8,
                'name'=>'VINLIDEN',
                'image'=>'810.jpg',
                'desc'=>'Cover for 2-seat sofa, Hakebo beige',
                'price'=>1600000,
                'stock'=>54,
            ],
            [
                'product_type_id'=>8,
                'name'=>'VALLENTUNA',
                'image'=>'811.jpg',
                'desc'=>'2-seat modular sofa, Orrsta olive-green',
                'price'=>15600000,
                'stock'=>37,
            ],
            [
                'product_type_id'=>8,
                'name'=>'DELAKTIG',
                'image'=>'812.jpg',
                'desc'=>'2-seat platform, Gunnared medium grey',
                'price'=>7095000,
                'stock'=>32,
            ],
        
            [
                'product_type_id'=>9,
                'name'=>'BRYGGJA',
                'image'=>'90.jpg',
                'desc'=>'Open wardrobe, dark grey',
                'price'=>3999000,
                'stock'=>39,
            ],
            [
                'product_type_id'=>9,
                'name'=>'RAKKESTAD',
                'image'=>'91.jpg',
                'desc'=>'Wardrobe with 3 doors, black-brown',
                'price'=>2399000,
                'stock'=>27,
            ],
            [
                'product_type_id'=>9,
                'name'=>'KLEPPSTAD',
                'image'=>'92.jpg',
                'desc'=>'Wardrobe with 2 doors, white',
                'price'=>1399000,
                'stock'=>42,
            ],
            [
                'product_type_id'=>9,
                'name'=>'BRIMNES',
                'image'=>'93.jpg',
                'desc'=>'Wardrobe with 3 doors, white',
                'price'=>2599000,
                'stock'=>39,
            ],
            [
                'product_type_id'=>9,
                'name'=>'MUSKEN',
                'image'=>'94.jpg',
                'desc'=>'Wardrobe with 2 doors+3 drawers, white',
                'price'=>3999000,
                'stock'=>10,
            ],
            [
                'product_type_id'=>9,
                'name'=>'TRYSIL',
                'image'=>'95.jpg',
                'desc'=>'Wardrobe, white/mirror glass',
                'price'=>3499000,
                'stock'=>16,
            ],
            [
                'product_type_id'=>9,
                'name'=>'SYVDE',
                'image'=>'96.jpg',
                'desc'=>'Open wardrobe, white',
                'price'=>2000000,
                'stock'=>48,
            ],
            [
                'product_type_id'=>9,
                'name'=>'VISTHUS',
                'image'=>'97.jpg',
                'desc'=>'Wardrobe, grey/white',
                'price'=>5999000,
                'stock'=>13,
            ],
            [
                'product_type_id'=>9,
                'name'=>'VUKU',
                'image'=>'98.jpg',
                'desc'=>'Wardrobe, white',
                'price'=>299000,
                'stock'=>39,
            ],
            [
                'product_type_id'=>9,
                'name'=>'SONGESAND',
                'image'=>'99.jpg',
                'desc'=>'Wardrobe, brown',
                'price'=>3499000,
                'stock'=>19,
            ],
            [
                'product_type_id'=>9,
                'name'=>'TYSSEDAL',
                'image'=>'910.jpg',
                'desc'=>'Wardrobe, white/mirror glass',
                'price'=>5999000,
                'stock'=>4,
            ],
            [
                'product_type_id'=>9,
                'name'=>'NORDKISA',
                'image'=>'911.jpg',
                'desc'=>'Open wardrobe with sliding door, bamboo',
                'price'=>3299000,
                'stock'=>18,
            ],
            [
                'product_type_id'=>9,
                'name'=>'HEMNES',
                'image'=>'912.jpg',
                'desc'=>'Open wardrobe, white stained',
                'price'=>2999000,
                'stock'=>28,
            ],
        ]);
    }
}